user  nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

 
    upstream backend {
        server backend:3000;
    }


    server {
        listen 80;
        server_name webantonio.nomorepartiessbs.ru 158.160.222.61;

        root /usr/share/nginx/html;
        index index.html;

  
        location /api/ {
            proxy_pass http://backend:3000/api/;
            proxy_http_version 1.1;

            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location /content/ {
            proxy_pass http://backend:3000/content/;
            proxy_http_version 1.1;

            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location / {
            try_files $uri $uri/ /index.html;
        }
    }


    server {
        listen 80;
        server_name api.webantonio.nomorepartiessbs.ru;

        location / {
            proxy_pass http://backend:3000;
            proxy_http_version 1.1;

            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
